bulker:
  volumes: ['$HOME']
  envvars: ['DISPLAY']
  host_network: true
  system_volumes: true
  registry_url: http://hub.bulker.io/
  shell_path: ${SHELL}
  shell_rc: $HOME/.bashrc
  rcfile: start.sh
  rcfile_strict: start_strict.sh
  apptainer_image_folder: ${HOME}/simages
  container_engine: docker
  default_namespace: bulker
